### ISSUE TITLE
Small graphical inconsistencies in the main page

### ISSUE THREAD

**Issue by lorenzo-filomena** [polito/nuova-pagina-studenti#1]
The main page has small inconsistencies when adapting the margins of the text fields to different windows ratios:

- The "Matricola" and the "Corso di laurea" fields collide.
   To reproduce:
    - Set language to Italian
    - Set window size to 1200 x 900

![immagine](https://github.com/user-attachments/assets/3f789b6f-1761-4b38-83e8-0d8f317da740)

- The date inside the Recent materials window gets cut off without the possibility to scroll left

![immagine](https://github.com/user-attachments/assets/39a822bb-c5da-40cc-ac39-e66018b5f0c8)

- The date of the virtual classrooms in the Recent Virtual Classrooms window is too close to the description of the Lesson

![immagine](https://github.com/user-attachments/assets/5aa45f1d-b1bb-4763-a03e-174dd42a71b5)

- The scroll menu of the Topics in the Help page is independent from the scroll of the page, meaning that in order to scroll the topics it is required to scroll down the page and then scroll the list of the topics

Tested on Firefox 133.0.3 Fedora Linux 41 Desktop

**Comment by andreaappendino** [comment]
Thank you for reporting this issue. We have fixed the graphical inconsistencies, and for the ticket integration, we have increased the container height while waiting for a more definitive fix.
