### ISSUE TITLE
Communications / notifications section

### ISSUE THREAD

**Issue by lorenzo-filomena** [polito/nuova-pagina-studenti#4]
The communications / notifications section has small inconsistencies in graphical appearance and behaviour:
- The name of the section is "Communications" but the filter selector calls them "notifications"
![immagine](https://github.com/user-attachments/assets/9dfc7637-2849-4cf3-83e6-67aa9bfba44b)

- The bell icon near the title behaves like a button, switching to the solid style when hovering on it

- When "Select all" is used, the "Segna come letti" and "Segna come non letti" buttons have different styles (one is always primary, the other switches between primary and outline when hovering), they are not translated to English and the horizontal alignment is, in my opinion, weirdly too much to the right. They are also  much bigger than the "select all" text

- The CPD questionnaires can be set as read as the other notifications, but they come back when refreshing the page. This is in my opinion a bit confusing, if they have to remain as unread i would expect that they cannot be set as read at all. I'm also questioning if they should be counted in the number of unread messages in the badge on the bell icon, but i can understand it could be a wanted behaviour

**Comment by andreaappendino** [comment]
Thank you for your feedback! The issues related to the buttons and translation have been fixed.

The notification about the CPD questionnaire is intentionally designed to remain in the "Communications" section even after being read. We will certainly consider your suggestion to improve the "Communications" section.
