### ISSUE TITLE
Delete links in services not working

### ISSUE THREAD

**Issue by Tizio0o0o0o** [polito/nuova-pagina-studenti#6]
**Describe the bug**
In services you can add new links but not delete existiing or new created one

**To Reproduce**
1. Go to the "services" page
2. Click on the trash bin of an existin link
3. See error "Parametroi non validi"

**Expected behavior**
The service should be deleted (non essential ones)

**Screenshots**
![image](https://github.com/user-attachments/assets/df51a4a5-a0c6-4f0a-bfb6-22422519946c)

**Comment by ValenteGiulia** [comment]
Thank you for bringing this to our attention. We have fixed the issue, and it should now be working.
